### PR TITLE
TOS

### PR DESCRIPTION
**Pull request by Bash-09**
- Add `tos_agreement_date` to preferences for web API
  - Set to empty string to reject
  - Set to valid ISO 8601 date time to say you agreed at that time
  - If not agreed or the agreement happened before the last TOS update, demo uploads are disabled

### CODE REVIEW

**Comment by Bash-09** [comment]
@megascatterbomb This will need to be tested, as I have not been able to test it.

**Comment by Seercat3160** [comment]
I'd think the TOS text (and checking accepted date vs most current) should be retrieved from the masterbase instance by the client-backend, and sent to the webui. That way, custom UIs can have proper support for TOS, and the TOS is properly based on the masterbase instance in use. How does that compare to the current ideas?

**Comment by Bash-09** [comment]
> I'd think the TOS text (and checking accepted date vs most current) should be retrieved from the masterbase instance by the client-backend, and sent to the webui. That way, custom UIs can have proper support for TOS, and the TOS is properly based on the masterbase instance in use. How does that compare to the current ideas?

To quote a message from Mega:
> tos changes would only happen when the user updates the client (as that's the only time our data collection practices would change)

So combined with the fact that plans are only to support a central Masterbase, I don't think it matters too much at the moment. In an ideal implementation I would agree with you but there's probably no need.

**Comment by megascatterbomb** [comment]
LGTM. Will hold approval until the matching functionality of the UI is complete and has been tested.

**Review by megascatterbomb — APPROVED** [review]
Approved; new functionality utilized by https://github.com/MegaAntiCheat/MegaAntiCheat-UI/pull/111#pullrequestreview-2206447688

**Pull request merged**
