### PR TITLE
Bash09/bundle UI

### PR DESCRIPTION
**Pull request by Bash-09**
I wasn't keen to sort out including the UI repo as a submodule and automating inlcluding a build of that at compile time. Instead I've opted to just leave it simple with a `ui` folder that you throw some files in, then they get compiled into the binary and served at runtime, this just means we will have to commit and update the ui files every now and then when the UI repo is updated.

### CODE REVIEW

**Comment by SammCheese** [comment]
I'd suggest automatically opening the URL of the UI on start of the backend

**Comment by Bash-09** [comment]
TODO: Add a UI build script for Windows

**Comment by SammCheese** [comment]
You are missing the installation for both pnpm (`npm add pnpm`) and npm/nodejs itself

**Comment by SammCheese** [comment]
> also to note that `pnpx` (which `pnpm run build` invokes via `pnpm run lint`) is set to be [deprecated](https://stackoverflow.com/a/70266473). Installs of `pnpm` these days do not bundle pnpx, at least not on windows. Thus `pnpm run build` results in a `pnpx is not recognized...` error.
> 
> This lint line should probably be fixed to use `pnpm exec`, but in the mean time you can still build and deploy on new `pnpm` installs using: `pnpm exec tailwind -i ./src/index.css -o ./src/tailwind.css` `pnpm exec webpack`
> 
> I guess this is more an issue for @SammCheese to resolve.

Fixed, we're using pnpm exec now

**Comment by Bash-09** [comment]
> You are missing the installation for both pnpm (`npm add pnpm`) and npm/nodejs itself

Fixed

**Comment by Bash-09** [comment]
It works for me, if we run into problems it should be trivial to modify the scripts to fix it. I'm gonna merge this mostly for convenience.

**Pull request merged**
